name = "ticket-page"
compatibility_date = "2026-02-27"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "ticketdatabase"
database_id = "e3d57332-3160-4043-9f4e-be4b728f5722"